name: Release WebUIFlasher Docker Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate release version
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          branch: main
          tag_prefix: "v"
          major_pattern: "/^(feat|fix|refactor)!:/"
          minor_pattern: "/^feat:/"
          search_commit_body: true

      - name: Log generated version
        run: echo "Version is ${{ steps.semver.outputs.version }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.semver.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.semver.outputs.version }}
            type=semver,pattern={{major}},value=${{ steps.semver.outputs.version }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.semver.outputs.version }}
          name: WebUIFlasher v${{ steps.semver.outputs.version }}
          body: |
            ## What's Changed
            
            Docker images available at:
            - `ghcr.io/${{ github.repository }}:${{ steps.semver.outputs.version }}`
            - `ghcr.io/${{ github.repository }}:latest`
            
            ### Usage
            ```bash
            # Standard setup (full /dev access)
            docker compose up -d
            
            # Secure setup (selected TTY devices)
            docker compose -f docker-compose.selected-tty.yaml up -d
            ```
            
            ### Supported Architectures
            - linux/amd64
            - linux/arm64
          draft: false
          prerelease: false
